// resort 13
import {
  maarUbud,
  seascapeUResort,
  seascapeSResort,
  aksariUbud,
  amareaUbud,
  asteraCanggu,
  asvaraUbud,
  atapCanggu,
  cabanaCanggu,
  dedaryUbud,
  kaamalaUbud,
  monolocaleSeminyak,
  sinivieSeminyak,
} from ".";
// Luxury 10
import {
  aksariSeminyak,
  alevaSeminyak,
  asteraSeminyak,
  asvaraGianyar,
  ayonaCanggu,
  ayonaSeminyak,
  cyrusBadung,
  eightpalmsSeminyak,
  sanavieSeminyak,
  terataiCanggu,
} from ".";
// Prmeium 8
import {
  hideoutKarangasem,
  inivieLegian,
  lavieLegian,
  sanoraSanur,
  sanctuarySeminyak,
  suaraalamUbud,
  theardenUluwatu,
  theJimbaran,
} from ".";
// Midscale 3
import { aeraCanggu, mancaCanggu, roomatesCanggu } from ".";
export const resortData = [
  {
    id: 1,
    background: maarUbud,
    image: maarUbud,
    name: "Maar Resort Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 2,
    background: seascapeUResort,
    image: seascapeUResort,
    name: "Seascape Uluwatu Resort & Spa",
    description: "Uluwatu, Bali",
  },
  {
    id: 3,
    background: asvaraUbud,
    image: asvaraUbud,
    name: "Asvara Resort Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 4,
    background: seascapeSResort,
    image: seascapeSResort,
    name: "Seascape Luxury Resort & Spa",
    description: "Denpasar, Bali",
  },
  {
    id: 5,
    background: sinivieSeminyak,
    image: sinivieSeminyak,
    name: "Sini Vie Luxury Reosrt & Spa Seminyak",
    description: "Seminyak, Bali",
  },
  {
    id: 6,
    background: kaamalaUbud,
    image: kaamalaUbud,
    name: "Kaamala Luxury Resort & Spa Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 7,
    background: aksariUbud,
    image: aksariUbud,
    name: "Aksari Luxury Resort & Spa Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 8,
    background: monolocaleSeminyak,
    image: monolocaleSeminyak,
    name: "Monolocale Luxury Resort & Spa Seminyak",
    description: "Seminyak, Bali",
  },
  {
    id: 9,
    background: dedaryUbud,
    image: dedaryUbud,
    name: "Dedary Resort & Spa Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 10,
    background: asteraCanggu,
    image: asteraCanggu,
    name: "Astera Luxury Resort & Spa Canggu",
    description: "Canggu, Bali",
  },
  {
    id: 11,
    background: amareaUbud,
    image: amareaUbud,
    name: "Amarea Resort & Spa Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 12,
    background: cabanaCanggu,
    image: cabanaCanggu,
    name: "Canggu Cabana Resort & Spa",
    description: "Canggu, Bali",
  },
  {
    id: 13,
    background: atapCanggu,
    image: atapCanggu,
    name: "Atap Resort Canggu",
    description: "Canggu, Bali",
  },
];
export const luxuryData = [
  {
    id: 1,
    background: aksariSeminyak,
    image: aksariSeminyak,
    name: "Aksari Villa",
    description: "Seminyak, Bali",
  },
  {
    id: 2,
    background: alevaSeminyak,
    image: alevaSeminyak,
    name: "Aleva Villa",
    description: "Seminyak, Bali",
  },
  {
    id: 3,
    background: asteraSeminyak,
    image: asteraSeminyak,
    name: "Astera Villa Seminyak",
    description: "Seminyak, Bali",
  },
  {
    id: 4,
    background: asvaraGianyar,
    image: asvaraGianyar,
    name: "Asvara Villa",
    description: "Denpasar, Bali",
  },
  {
    id: 5,
    background: ayonaCanggu,
    image: ayonaCanggu,
    name: "Ayona Villa Canggu",
    description: "Seminyak, Bali",
  },
  {
    id: 6,
    background: ayonaSeminyak,
    image: ayonaSeminyak,
    name: "Ayona Villa Seminyak",
    description: "Ubud, Bali",
  },
  {
    id: 7,
    background: cyrusBadung,
    image: cyrusBadung,
    name: "Cyrus Villa",
    description: "Ubud, Bali",
  },
  {
    id: 8,
    background: eightpalmsSeminyak,
    image: eightpalmsSeminyak,
    name: "Eight Palms Villa",
    description: "Seminyak, Bali",
  },
  {
    id: 9,
    background: sanavieSeminyak,
    image: sanavieSeminyak,
    name: "Sana Vie Villa",
    description: "Ubud, Bali",
  },
  {
    id: 10,
    background: terataiCanggu,
    image: terataiCanggu,
    name: "Teratai Canggu",
    description: "Canggu, Bali",
  },
];
export const premiumData = [
  {
    id: 1,
    background: hideoutKarangasem,
    image: hideoutKarangasem,
    name: "Hideout",
    description: "Seminyak, Bali",
  },
  {
    id: 2,
    background: inivieLegian,
    image: inivieLegian,
    name: "Ini Vie Villa",
    description: "Seminyak, Bali",
  },
  {
    id: 3,
    background: lavieLegian,
    image: lavieLegian,
    name: "La Vie Villa",
    description: "Seminyak, Bali",
  },
  {
    id: 4,
    background: sanoraSanur,
    image: sanoraSanur,
    name: "Sanora Villa ",
    description: "Sanur, Bali",
  },
  {
    id: 5,
    background: sanctuarySeminyak,
    image: sanctuarySeminyak,
    name: "Sanctuary Villa Seminyak",
    description: "Seminyak, Bali",
  },
  {
    id: 6,
    background: suaraalamUbud,
    image: suaraalamUbud,
    name: "Suara Alam Ubud",
    description: "Ubud, Bali",
  },
  {
    id: 7,
    background: theardenUluwatu,
    image: theardenUluwatu,
    name: "The Arden Villa Uluwatu",
    description: "Uluwatu, Bali",
  },
  {
    id: 8,
    background: theJimbaran,
    image: theJimbaran,
    name: "The Jimbaran Villa",
    description: "Jimbaran, Bali",
  },
];
export const midscaleData = [
  {
    id: 1,
    background: aeraCanggu,
    image: aeraCanggu,
    name: "Aeera Villa",
    description: "Canggu, Bali",
  },
  {
    id: 2,
    background: mancaCanggu,
    image: mancaCanggu,
    name: "Manca Villa",
    description: "Canggu, Bali",
  },
  {
    id: 3,
    background: roomatesCanggu,
    image: roomatesCanggu,
    name: "Roomates",
    description: "Canggu, Bali",
  },
  {
    id: 4,
    background: aeraCanggu,
    image: aeraCanggu,
    name: "Aeera Villa",
    description: "Canggu, Bali",
  },
  {
    id: 5,
    background: mancaCanggu,
    image: mancaCanggu,
    name: "Manca Villa",
    description: "Canggu, Bali",
  },
];
