import {
  wonderAnkhusaUbud,
  wonderCantinaClasseCangguBadung,
  wonderCantinaClasseUbud,
  wonderFlairsUbudGianyar,
  wonderHabitatBistroUbud,
  wonderKojinTeppanyakiUbud,
  wonderMaiMainPlaygroundBadung,
  wonderNoriiUbud,
  wonderPaedThaiCanggu,
  wonderPaedThaiSanur,
  wonderSanctuaryUmalasBadung,
  wonderSansIndianGianyar,
  wonderSeabirdCanggu,
  wonderSevenPaintingUbud,
  wonderShicirinCanggu,
  wonderShicirinSeminyak,
  wonderShicirinUbud,
  wonderTerraVerteUbudGianyar,
  wonderTheJungleClubUbudGianyar,
  wonderTropicalTemptationBeachClubBadung,
  wonderTsuneSeminyak,
  wonderTsuneUluwatuBadung,
  wonderWorkmatesCanggu,
} from ".";

export const wonderData = [
  {
    id: 1,
    Img: wonderAnkhusaUbud,
    name: "Ankhusa Restaurant Ubud",
    destination: "Ubud, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 2,
    Img: wonderCantinaClasseCangguBadung,
    name: "Cantina Classe Canggu ",
    destination: "Badung, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 3,
    Img: wonderCantinaClasseUbud,
    name: "Cantina Classe Ubud",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 4,
    Img: wonderFlairsUbudGianyar,
    name: "Flairs Ubud",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 5,
    Img: wonderHabitatBistroUbud,
    name: "Habitat Bistro",
    destination: "Ubud, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 6,
    Img: wonderKojinTeppanyakiUbud,
    name: "Kojin Teppanyaki",
    destination: "Ubud, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 7,
    Img: wonderMaiMainPlaygroundBadung,
    name: "Mai Main Playground",
    destination: "Badung, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 8,
    Img: wonderNoriiUbud,
    name: "Norii Ubud",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 9,
    Img: wonderPaedThaiCanggu,
    name: "Paed Thai Canggu",
    destination: "Canggu, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 10,
    Img: wonderPaedThaiSanur,
    name: "Paed Thai Sanur",
    destination: "Sanur, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 11,
    Img: wonderSanctuaryUmalasBadung,
    name: "Sanctuary Umalas",
    destination: "Badung, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 12,
    Img: wonderSansIndianGianyar,
    name: "Sans Indian",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 13,
    Img: wonderSeabirdCanggu,
    name: "Seabird",
    destination: "Canggu, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 14,
    Img: wonderSevenPaintingUbud,
    name: "Seven Painting",
    destination: "Ubud, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 15,
    Img: wonderShicirinCanggu,
    name: "Shicirin Canggu",
    destination: "Canggu, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 16,
    Img: wonderShicirinSeminyak,
    name: "Shicirin Seminyak",
    destination: "Seminyak, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 17,
    Img: wonderShicirinUbud,
    name: "Shicirin Ubud",
    destination: "Ubuds, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 18,
    Img: wonderTerraVerteUbudGianyar,
    name: "Terra Verte Ubud",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 19,
    Img: wonderTheJungleClubUbudGianyar,
    name: "The Jungle Club Ubud",
    destination: "Gianyar, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 20,
    Img: wonderTropicalTemptationBeachClubBadung,
    name: "Tropical Temptation Beach Club",
    destination: "Badung, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 21,
    Img: wonderTsuneSeminyak,
    name: "Tsune Seminyak",
    destination: "Seminyak, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 22,
    Img: wonderTsuneUluwatuBadung,
    name: "Tsune Uluwatu",
    destination: "Badung, Bali",
    rating: "⭐ 5.00",
  },
  {
    id: 23,
    Img: wonderWorkmatesCanggu,
    name: "Workmates Canggu",
    destination: "Canggu, Bali",
    rating: "⭐ 5.00",
  },
];
